services:
  - type: web
    name: quick-test
    runtime: node
    prebuildCommand: |
      npm ci
      npx playwright install
    buildCommand: npm install && npm run backend:build:prod
    startCommand: npm run backend:start:prod
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
      - key: CI
        value: true
