services:
  - type: web
    name: quick-test
    env: node
    buildCommand: |
      npm install
      npx playwright install
    startCommand: npm start
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
